version: '3.6'
services:
  mariadb:
    #image: jsurf/rpi-mariadb
    image: mariadb:latest
    container_name: mariadb_weather
    hostname: sqlserver
    environment:
      MYSQL_USER: weather
      MYSQL_PASSWORD: weather
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: weather
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - mariadb-weather-data:/var/lib/mysql

  webserver:
    image: ghcr.io/markusjx/weather_dashboard/jvm:latest
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      # Environment file
      - "./.env.example:/work/.env"
      # JWT RSA keys
      - "./jwtPublicKey.pem:/work/jwtPublicKey.pem"
      - "./jwtPrivateKey.pem:/work/jwtPrivateKey.pem"
      # Key files for ssl support
      #- "./ssl.crt:/work/ssl.crt"
      #- "./ssl.key:/work/ssl.key"

# Store the database permanently
volumes:
  mariadb-weather-data: