# Create the actual runner
FROM adoptopenjdk/openjdk11:debianslim-jre
WORKDIR /work
COPY build/quarkus-app /work
RUN chmod 775 /work
EXPOSE 8080
EXPOSE 8443
CMD ["java", "-jar", "quarkus-run.jar", "-Dquarkus.http.host=0.0.0.0"]