# Build the native executable
FROM ghcr.io/graalvm/graalvm-ce:latest AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN gu install native-image
RUN chmod +x gradlew
RUN ./gradlew -b /usr/src/app/build.gradle clean build -Dquarkus.package.type=native

# Create the runner
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/build/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
EXPOSE 8443
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
