name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Buildx Runner
        run: docker buildx create --platform linux/amd64,linux/arm/v7,linux/arm64 --use
      - name: Docker build
        run: docker buildx build -t ghcr.io/markusjx/weather_dashboard:latest --platform linux/amd64,linux/arm/v7,linux/arm64 --pull --push .
